name: pypsa-doc
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - six
  - numpy
  - pyomo>=5.7.0
  - scipy
  - pandas>=0.24.0
  - pytables
  - matplotlib
  - networkx>=1.10
  - pyomo
  - cartopy>=0.16
  - coincbc

  - pip:
    - .
    - sphinx
    - sphinx_rtd_theme
